[package]
name = "discord-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Cliente desktop com captura de tela nativa"

[lib]
name = "discord_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow.workspace = true
capture = { path = "../../../crates/capture" }
media = { path = "../../../crates/media" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-deep-link = "2.4.10"
tauri-plugin-opener = "2.5.5"
tauri-plugin-process = "2.3.1"
tauri-plugin-updater = "2.11.0"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
